# Generated by Django 2.2.7 on 2019-11-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdata',
            old_name='CfApiPassword',
            new_name='CFApiPassword',
        ),
        migrations.RenameField(
            model_name='applicationdata',
            old_name='CfApiUserId',
            new_name='CFApiUserId',
        ),
        migrations.RenameField(
            model_name='applicationdata',
            old_name='CfRequestId',
            new_name='CFRequestId',
        ),
        migrations.RenameField(
            model_name='applicationdata',
            old_name='FilterId',
            new_name='FilterID',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='TaxId',
            new_name='TaxID',
        ),
        migrations.AddField(
            model_name='business',
            name='ApplicationData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.ApplicationData'),
        ),
        migrations.AddField(
            model_name='owner',
            name='Business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.Business'),
        ),
    ]
